define(['require', 'app'], function(require, APP) {

    /**
     * Controller for Screen1 generated by Appery.io
     * @module Screen1
     */

    APP.controller('Screen1', ['$scope', 'Apperyio', controller]);

    function controller($scope, Apperyio) {
        $scope.name = 'Screen1Controller';
        $scope.screenName = 'Screen1';
        $scope.Apperyio = Apperyio;

        /**
         * $routeParams has dictionary with all named params for current route
         * @type {Object}
         */
        var $routeParams = Apperyio.get("$routeParams");
        $scope.$routeParams = $routeParams;

        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            // On load screen logic
        }

        /**
         * user controller variables
         */
    }

});