define(['require'], function(require) {

    /**
     * Controller for index generated by Appery.io
     * @module index
     */

    function controller($scope, Apperyio) {
        $scope.name = 'indexController';
        $scope.screenName = 'index';
        $scope.Apperyio = Apperyio;

        /**
         * $routeParams has dictionary with all named params for current route
         * @type {Object}
         */
        var $routeParams = Apperyio.get("$routeParams");
        $scope.$routeParams = $routeParams;

        /**
         * User controller functions
         */
        /**
         * @function init
         */
        $scope.init = function() {
            //On load screen logic
        }

        /**
         * user controller variables
         */
    }

    return ['$scope', 'Apperyio', controller];

});